import { Employee, Task } from '../types/task';

export const mockEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Sunita Choudhury',
    email: 'sunita.choudhury@company.com',
    role: 'member',
    designation: 'Full Stack Developer',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  },
  {
    id: 'emp-2',
    name: 'Yash Majumdar',
    email: 'yash.majumdar@company.com',
    role: 'member',
    designation: 'UI/UX Product Designer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 'emp-3',
    name: 'Ritu Paul',
    email: 'ritu.paul@company.com',
    role: 'member',
    designation: 'DevOps & Cloud Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  },
  {
    id: 'emp-4',
    name: 'Rajesh Goyal',
    email: 'rajesh.goyal@company.com',
    role: 'admin',
    designation: 'Scrum Master',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
  {
    id: 'emp-5',
    name: 'Alka Bansal',
    email: 'alka.bansal@company.com',
    role: 'member',
    designation: 'Software Quality Analyst',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
  },
  {
    id: 'emp-6',
    name: 'Deepak Thakur',
    email: 'deepak.thakur@company.com',
    role: 'member',
    designation: 'Senior Frontend Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-101',
    title: 'Perform Annual Architecture Review & Technical Debt Cleanup',
    description: 'Upgrade deprecated npm dependencies, optimize bundle sizes and streamline Docker staging pipeline.',
    status: 'todo',
    priority: 'low',
    assignedTo: 'emp-1',
    dueDate: '2026-08-16',
    createdAt: '2026-08-01',
    attachments: [],
  },
  {
    id: 'task-102',
    title: 'Design Dashboard Wireframes & High-Fidelity Design System',
    description: 'Create low-fidelity and high-fidelity wireframes for the workspace task manager dashboard.',
    status: 'in_progress',
    priority: 'high',
    assignedTo: 'emp-2',
    dueDate: '2026-08-20',
    createdAt: '2026-08-02',
    attachments: [],
  },
  {
    id: 'task-103',
    title: 'Implement Auth Middleware & RBAC Security Layer',
    description: 'Secure API routes and pages using custom JWT token validation middleware with role checks.',
    status: 'completed',
    priority: 'urgent',
    assignedTo: 'emp-3',
    dueDate: '2026-08-22',
    createdAt: '2026-08-03',
    attachments: [],
  },
  {
    id: 'task-104',
    title: 'Document RAG Pipeline & Vector Indexing Engine',
    description: 'Index company SOP documents and configure retrieval-augmented semantic search.',
    status: 'in_progress',
    priority: 'medium',
    assignedTo: 'emp-4',
    dueDate: '2026-08-25',
    createdAt: '2026-08-05',
    attachments: [],
  },
  {
    id: 'task-105',
    title: 'Realtime Communication Hub & Announcements Channel',
    description: 'Integrate WebSocket channels for instant team messaging and push alert broadcasting.',
    status: 'todo',
    priority: 'high',
    assignedTo: 'emp-5',
    dueDate: '2026-08-28',
    createdAt: '2026-08-06',
    attachments: [],
  },
  {
    id: 'task-106',
    title: 'Automated Attendance & Biometric Geo-Fence Verification',
    description: 'Validate employee check-in times and calculate monthly overtime hours automatically.',
    status: 'completed',
    priority: 'medium',
    assignedTo: 'emp-6',
    dueDate: '2026-08-30',
    createdAt: '2026-08-08',
    attachments: [],
  },
];
